- .github/workflows/release.yml
> Change the release type in ci.yml

- .travis.yml
- Ballerina.lock
- Ballerina.toml
- README.md
- src/slack/slack_client.bal
- src/slack/slack_error.bal
- src/slack/slack_types.bal
- src/slack/tests/main_test.bal
- src/slack/utils.bal
Migrate the code of this repository to Ballerina Swan Lake Preview1 version.
Migrate the code of this repository to Ballerina Swan Lake Preview1 version.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
- Ran FindSecurityBugs plugin and verified report?no
N/A
N/A
N/A
JDK 1.8, Ubuntu 18.04
N/A
> Migrate the code to Ballerina Swan Lake Preview1

- Ballerina.lock
- README.md
- src/slack/slack_client.bal
- src/slack/slack_error.bal
- src/slack/utils.bal
Migrate the the Slack connector code to Ballerina 2.0.0-Preview1.
Code migration.
Fixes were mainly introduced to init() and definition of Errors.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
This was tested on a Ballerina 2.0.0-SNAPSHOT pack which was built on 16th June 2020.
JDK 1.8, Ubuntu 18.04
N/A
> Migrate the code to ballerina 2.0.0-Preview1

- .github/workflows/ci.yml
- .github/workflows/release.yml
Update ballerina github action branch
> Update ballerina github action branch

- Ballerina.lock
- Ballerina.toml
- src/slack/Module.md
Update the module.md with the correct version
> Update the module.md with the correct version

- Ballerina.lock
- Ballerina.toml
- README.md
- src/slack/Module.md
- src/slack/slack_client.bal
- src/slack/tests/main_test.bal
Update docs in slack connector.
> Fix docs in slack connector

- .github/workflows/ci.yml
- src/slack/tests/main_test.bal
> Update credentials names

- .travis.yml
> Fix issue in the travis.yml file when migrating to SLP 7
> Migration to SLP 7 (#14)
> Migration to Swan Lake Preview 7 Release
> JDK11, ballerina Swan Lake Priview 7, Ubuntu
> Update Migration to SLP 7

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Ballerina.toml
> Adding  a temporary workaround for issue#27405
> Adding workaround for issue#27405

- metadata/slack.json
> To add display names for UI needs
> Make slack connector available for user friendly  way
> Added new slack.json file
> Metadata File Addition for UI Purposes

- metadata/slack.json
> To add listener annotation to slack.json and few other format changes
>  Metadata File Addition for UI Purposes (#17)
> Metadata File Update for UI Purposes

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- .travis.yml
- Ballerina.toml
- Module.md
- Package.md
- README.md
- slack_client.bal
- tests/main_test.bal
- utils.bal
> Migration Swan Lake Preview8

- Module.md
- Package.md
- README.md
- slack_client.bal
- tests/main_test.bal
> Having multiple clients according to the functional differences of each methods had identified as not convenient in the users point of view
> Merge multiple clients in to single clients and allow users to call all the methods through that client
> Ballerina Swan Lake Preview 8, Ubuntu
> Merging multiple clients into single client

- Ballerina.toml
> since the previous released version is 0.9.5, changing the latest version to 0.9.6
- Ran FindSecurityBugs plugin and verified report? yes/no
> Change version to 0.9.6

- slack/utils.bal
- Fix https://github.com/wso2-enterprise/choreo/issues/4660
- Fix the way of handling http response
> Ballerina Swan Lake beta.1
> Fix http response handling

- gradle.properties
- slack/Dependencies.toml
- slack/resources/Channel_data.json
- slack/resources/Conversations_data.json
- slack/resources/FileInfo_data.json
- slack/resources/Message_data.json
- slack/resources/Profile_data.json
- slack/resources/Purpose_data.json
- slack/resources/ResponseMetadata_data.json
- slack/resources/Topic_data.json
- slack/resources/User_data.json
> Bump dependency versions to Ballerina SLBeta2
> Bump dependency versions for Ballerina SLBeta2

- slack/Module.md
$subject
JDK 11
Ballerina SLBeta2
> Add bal run command step in Module.md

- slack/modules/listener/Module.md
$subject
JDK 11
Ballerina SLBeta
> Add bal run step in listener Module.md

- README.md
- slack/Dependencies.toml
- slack/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
JDK 11
Ballerina SLBeta3-SNAPSHOT
> Bump versions for slbeta3 in master branch

- gradle.properties
- samples/client/getConversationHistory.bal
- samples/client/getConversationMembers.bal
- slack/Dependencies.toml
- slack/endpoint.bal
- slack/stream_implementer.bal
- slack/tests/main_test.bal
- Bump dependency versions
- Fix stream related breaking change, test cases, samples
JDK 11
Ballerina SLBeta3
> Migrate to slbeta3

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
- README.md
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
- Add slbeta4 migration changes
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
> Update ballerina commands

- slack/modules/listener/http_service.bal
- slack/modules/listener/listener.bal
- slack/modules/listener/simple_http_service.bal
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/156
- Make SimpleHttpService service type distinct
> Fix listener service related build failure

- slack/endpoint.bal
Modify icon as per new requirements 
- Removed .svg icon and added .png icon
- Icon size 200 x 200 px 
- Mention the icon in `Ballerina.toml` so that Ballerina central will render the connector icon
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/179
- Improved connector icon
Please delete options that are not relevant.
N/A
N/A
> Modify icon path in client.bal

- slack/tests/main_test.bal
- slack/utils.bal
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/197
> Fix warning messages in the build

- slack/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
> Re-generate Dependencies.toml with latest pack

- samples/client/archiveConversation.bal
- samples/client/deleteFile.bal
- samples/client/getConversationHistory.bal
- samples/client/getConversationInfo.bal
- samples/client/getConversationMembers.bal
- samples/client/getFileInfo.bal
- samples/client/getUserInfoByUserId.bal
- samples/client/getUserInfoByUsername.bal
- samples/client/joinConversation.bal
- samples/client/leaveConversation.bal
- samples/client/listConversations.bal
- samples/client/listFiles.bal
- samples/client/listUserConversations.bal
- samples/client/lookupUserByEmail.bal
- samples/client/postMessage.bal
- samples/client/removeUser.bal
- samples/client/unarchiveConversation.bal
- samples/client/uploadFile.bal
- slack/Dependencies.toml
- slack/endpoint.bal
- slack/modules/listener/http_service.bal
- slack/stream_implementer.bal
- slack/tests/data-generator/data-generator.bal
- slack/tests/main_test.bal
- slack/utils.bal
$Subject
Fixes # (issue)
https://github.com/ballerina-platform/ballerina-extended-library/issues/264
Related Pull Requests (remove if not relevant)
- https://github.com/ballerina-platform/module-ballerinax-sfdc/pull/231
- Fix Ballerina anti-pattern codes according to [the guidelines](https://docs.google.com/document/d/1y6QVqaZzZt9jMpYV4jP5WRS_W_KoC4y40Uuoh1ALu8E/edit#heading=h.kel062m2vr8k).
Tested for all the available test cases
* Ballerina Version: Ballerina 2201.0.0
* Operating System: Ubuntu 20.04
* Java SDK: 11
> Fix ballerina anti-pattern codes in the codebase

- gradle.properties
- slack/Ballerina.toml
- slack/Dependencies.toml
- slack/Package.md
prepare connector for Swan Lake `2201.0.0` release
> prepare connector for `2201.0.0` release

- gradle.properties
- slack/Ballerina.toml
- slack/Package.md
- slack/endpoint.bal
- slack/tests/main_test.bal
- slack/utils.bal
- Implement `getChannelName` remote function
- Fix https://github.com/ballerina-platform/ballerina-extended-library/issues/340
> Implement `getChannelName` remote function

- slack/Ballerina.toml
- slack/Dependencies.toml
- slack/Package.md
- slack/config-types.bal
- slack/endpoint.bal
- slack/types.bal
- Alter ConnectionConfig record 
- Bump connector version and ballerina version in Ballerina.toml
- Bump ballerina version in Package.md
- Update Dependencies.toml with Ballerina 2201.2.0
> Alter ConnectionConfig record

- README.md
- slack/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
> Update Slack channel occurrences with Discord

- slack/Ballerina.toml
- slack/Dependencies.toml
- slack/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
> Update to Ballerina version 2201.3.0

- slack/tests/main_test.bal
$Subject. It will retry upon the specific error. 
Retry interval is 30 seconds. Sometimes it takes like 2 iterations to succeed when testing. 
Related issue: https://github.com/wso2-enterprise/choreo/issues/16598
> Improve tests to retry over ratelimited error

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
- .github/workflows/pull-request.yml
$subject.
Fixes https://github.com/ballerina-platform/ballerina-extended-library/issues/569
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Fix working-directory when running tests in workflows

- .github/workflows/ci.yml
- .github/workflows/daily-build.yml
$subject
Related to https://github.com/ballerina-platform/ballerina-library/issues/6142
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
* Ballerina Version:
* Operating System:
* Java SDK:
> Disable build failure notifications

- examples/survey-feedback-analysis/main.bal
- examples/survey-feedback-analysis/types.bal
Create types.bal file
Make variables constant and remove redundant checks
> Fix survey example

- docs/spec/openapi.json
> Remove problematic character in the title
